### ISSUE TITLE
Database entries can be added/edited by just a bone prefill

### ISSUE THREAD

**Issue by phorward** [viur-framework/vi-admin#49]
> Will be solved in the admin
> - Filter out error of bones where client data was missing
> - Use `bounce`

_Originally posted by @sveneberth in https://github.com/viur-framework/viur-core/issues/1220#issuecomment-2437545907_

**Comment by sveneberth** [comment]
Solved in https://github.com/viur-framework/vi-vue-components/commit/59be87284f36051e848d47189da9db577ee48321

**Comment by phorward** [comment]
I'm still not happy with this fix.

Now I'm getting cases like this one, just when performing a new "Add" in a List-module without any inputs or prefills:

<img width="927" height="622" alt="Image" src="https://github.com/user-attachments/assets/f77bdc20-bbec-405c-908b-d56e345d35a2" />

**Comment by ArneGudermann** [comment]
https://github.com/viur-framework/vi-vue-utils/pull/22 fix thix error for now.
